kind: project
metadata:
  name: stress-mlrun-project-amite
  created: '2023-06-26T08:48:27.972000'
spec:
  functions:
  - url: jobs_func.py
    name: normal_job_sec
    kind: job
    image: mlrun/mlrun
    handler: func_sec
  - url: jobs_func.py
    name: normal_job_min
    kind: job
    image: mlrun/mlrun
    handler: func_min
  - url: jobs_func.py
    name: normal_job_hour
    kind: job
    image: mlrun/mlrun
    handler: func_hour
  - url: ./dask_jobs_func.py
    name: dask_func
    kind: job
    image: mlrun/ml-models
    handler: train
  - url: nuclio_func.py
    name: nuclio_func
    kind: nuclio
    image: mlrun/mlrun
    handler: handler
  - url: jobs_func.py
    name: func
    kind: job
    image: mlrun/mlrun
    handler: func
  - url: jobs_func.py
    name: normal-job-sec
    kind: job
    image: mlrun/mlrun
    handler: func_sec_dataset
  - url: jobs_func.py
    name: normal-job-min
    kind: job
    image: mlrun/mlrun
    handler: func_min
  - url: jobs_func.py
    name: normal-job-hour
    kind: job
    image: mlrun/mlrun
    handler: func_hour_artifact
  - url: ./dask_jobs_func.py
    name: dask-func
    kind: job
    image: mlrun/ml-models
    handler: train
  - url: nuclio_func.py
    name: nuclio-func
    kind: nuclio
    image: mlrun/mlrun
    handler: handler
  - url: jobs_func.py
    name: func-artifact
    kind: job
    image: mlrun/mlrun
    handler: func_artifact
  workflows:
  - path: workflow.py
    name: workflow-func
  artifacts: []
  conda: ''
  source: ''
  desired_state: online
  owner: amite
  build:
    commands: []
    requirements: []
  custom_packagers: []
status:
  state: online
